### ISSUE TITLE
Support for 'makeWidget' mode

### ISSUE THREAD

**Issue by jyliang** [ubdi/react-native-typeform-embed#3]
Thanks for creating this convenient library!
The current 'makePopup' mode creates a close button at the top right of the window, is there a way to get rid of it? I see the current code is not using the 'makeWidget' mode. I tried to bring this mode in but it's not rendering on my end. Did you encounter a similar issue with the 'makeWidget' mode?

**Comment by harunsmrkovic** [comment]
Yeah, unfortunately it seems like `makePopup` is not supported. We were using it in the beginning, but it then just stopped working - https://github.com/ubdi/react-native-typeform-embed/commit/868e2a75a5bbe30c6060e00d9a9bb28393a6ee1f#diff-168726dbe96b3ce427e7fedce31bb0bc
